### PR TITLE
Account deletion, account edit fix-ups

### LINKED ISSUE #304: Implement account deletion
Blocked by eternagame/website#95

### PR DESCRIPTION
**Pull request by luxaritas**
Resolves #304

### CODE REVIEW

File: src/views/players/EditProfile/components/EditPlayerDanger.vue [hunk 1]
```diff
@@ -0,0 +1,173 @@
...
+        />
+        <transition name="fade">
+          <b-alert class="mt-3" show variant="danger" v-if="errorMessage">
+            {{ errorMessage }}
+          </b-alert>
+        </transition>
+        <b-btn variant="danger" @click="deleteAccount()" :disabled="loading">
+          Delete Account
+          <b-spinner v-if="loading" small />
+        </b-btn>
```
Comment (Qmtfive) [inline src/views/players/EditProfile/components/EditPlayerDanger.vue:53]: Should the modal also have a cancel button?

**Review by Qmtfive — CHANGES_REQUESTED** [review]

File: src/views/players/EditProfile/components/EditPlayerDanger.vue (hunk 1 above)
Comment (luxaritas) [reply src/views/players/EditProfile/components/EditPlayerDanger.vue:53]: Definitely!
